- name: Remove the default input reject all iptable rule
  lineinfile:
    path: /etc/iptables/rules.v4
    state: absent
    regexp: "-A INPUT -j REJECT --reject-with icmp-host-prohibited"
  when: ansible_distribution == "Ubuntu"

- name: Remove the default input reject all iptable rule
  lineinfile:
    path: /etc/iptables/rules.v4
    state: absent
    regexp: "-A FORWARD -j REJECT --reject-with icmp-host-prohibited"
  when: ansible_distribution == "Ubuntu"

- name: Disable firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: ansible_distribution == "OracleLinux"